// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo9hNtr4xmvIWdUmX5tz_J7riABgTnw-o',
    appId: '1:995397077164:web:1de719254cc31a6fea7709',
    messagingSenderId: '995397077164',
    projectId: 'healtcare-d3fa6',
    authDomain: 'healtcare-d3fa6.firebaseapp.com',
    storageBucket: 'healtcare-d3fa6.firebasestorage.app',
    measurementId: 'G-3K1C7QD6H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCl2GONJt2fgLvd_ll_hejQIgjm8llhks',
    appId: '1:995397077164:android:d4b7262a53e5a026ea7709',
    messagingSenderId: '995397077164',
    projectId: 'healtcare-d3fa6',
    storageBucket: 'healtcare-d3fa6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNDe5HqmqdR51PJcIn7ejjnaG0p7LHtHc',
    appId: '1:995397077164:ios:abd05c712e4a0ee1ea7709',
    messagingSenderId: '995397077164',
    projectId: 'healtcare-d3fa6',
    storageBucket: 'healtcare-d3fa6.firebasestorage.app',
    iosClientId: '995397077164-7qu7fdcgd0kmefql2af82bv8odobsmpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthcare',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNDe5HqmqdR51PJcIn7ejjnaG0p7LHtHc',
    appId: '1:995397077164:ios:abd05c712e4a0ee1ea7709',
    messagingSenderId: '995397077164',
    projectId: 'healtcare-d3fa6',
    storageBucket: 'healtcare-d3fa6.firebasestorage.app',
    iosClientId: '995397077164-7qu7fdcgd0kmefql2af82bv8odobsmpv.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo9hNtr4xmvIWdUmX5tz_J7riABgTnw-o',
    appId: '1:995397077164:web:d40e3bdd17c37f74ea7709',
    messagingSenderId: '995397077164',
    projectId: 'healtcare-d3fa6',
    authDomain: 'healtcare-d3fa6.firebaseapp.com',
    storageBucket: 'healtcare-d3fa6.firebasestorage.app',
    measurementId: 'G-5S41QFMRCM',
  );
}
